### ISSUE TITLE
Enquiries about the results of the solar dataset presented in Figure 9 of the paper

### ISSUE THREAD

**Issue by KeplerrC** [Y-debug-sys/Diffusion-TS#10]
Hi author, can you please provide me with the training code or script, I found that I can't reproduce the results of this experiment

**Comment by Y-debug-sys** [comment]
Hi, I don't know if your problem has been solved, but see [new Tutorial](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Tutorial_2.ipynb) please.
