### ISSUE TITLE
怎么查看评估指标的结果

### ISSUE THREAD

**Issue by 153201121yf** [Y-debug-sys/Diffusion-TS#11]
您好，我按照你的readme文件的要求，完成了运行和采样，也生成了output文件，但是我不知道应该怎么查看Context_FID等四项评价的数值，我运行后在终端没有出现结果，应该去哪里查看呢？ 请您指点，不胜感激

**Comment by Y-debug-sys** [comment]
Hello, see Tutorials in Experiments folder please.

**Comment by 153201121yf** [comment]
> 您好，请参阅 Experiments 文件夹中的 .ipynb 文件。

非常感谢老师的回复，我在jupyter notebook上运行了，但是我得到的结果很奇怪，我很困惑，请求您能再给我一些指导，麻烦老师您了
![e466a95337c41eec2424525b2985910](https://github.com/Y-debug-sys/Diffusion-TS/assets/150432118/d5316621-ccaa-45b1-b212-8ab9cf061bbd)

**Comment by Y-debug-sys** [comment]
你好，演示所用的sine数据集ori_data用的是保存的名字带有ground_truth的npy文件，但是其它数据集应当是名字带有norm_truth的npy文件，之前有问题[issue](https://github.com/Y-debug-sys/Diffusion-TS/issues/3)提到过。

**Comment by 153201121yf** [comment]
> 你好，演示所用的sine数据集ori_data用的是保存的名字带有ground_truth的npy文件，但是其它数据集应当是名字带有norm_truth的npy文件，之前有问题[issue](https://github.com/Y-debug-sys/Diffusion-TS/issues/3)提到过。

谢谢老师的指导，我重新去运行试试

**Comment by 153201121yf** [comment]
> 好，演示所用的正弦数据集ori_data用的是保存的名称为ground_truth的npy文件，但是其他数据集应该是名称为norm_truth的npy文件，之前提到过你的问题[。](https://github.com/Y-debug-sys/Diffusion-TS/issues/3)

老师您好，我重新run了之后发现context-fid还是差别很大，请老师指点一下，还有一个问题是这个context-fid等四项评估指标是只针对于Unconstrained任务是吗？ 非常感谢老师的指导
![af6700a6308bf69b3f03b118928d9d4](https://github.com/Y-debug-sys/Diffusion-TS/assets/150432118/5025bb4e-8e0e-4741-8d5b-6cd2dd3e17e9)

**Comment by Y-debug-sys** [comment]
由于取样问题，结果可能比较随机，需要多跑几轮。是的，condition生成只使用了mse或者mae。

**Comment by L402L** [comment]
老师 请问您消融实验部分会出代码和教程吗

**Comment by 153201121yf** [comment]
> 由于取样问题，结果可能比较随机，需要多跑几轮。是的，condition生成只使用了mse或者mae。

好的，谢谢老师的指导

**Comment by Y-debug-sys** [comment]
你好，后续可能会整理上传。
