### ISSUE TITLE
执行序列预测任务的输出保存在何方？

### ISSUE THREAD

**Issue by homehow358** [Y-debug-sys/Diffusion-TS#12]
作者您好，向您请教：
为了对股票数据集进行20个长度的预测时，执行如下的命令行代码：
`python main.py --name StockPredict20 --config_file ./Config/stocks.yaml --gpu 0 --sample 1 --milestone 10  --mode predict --pred_len 20`
输出如下图：
![1](https://github.com/Y-debug-sys/Diffusion-TS/assets/155547997/b2ca7439-69e4-49f4-b82c-3fb2b901c151)

ddpm_predict_StockPredict20.npy的'shape': (366, 24, 6), } 为什么是366而不是20呢？20个长度的预测输出到哪里去了呢？
当我进行10个长度的预测时，执行如下的代码：
`python main.py --name StockPredict --config_file ./Config/stocks.yaml --gpu 0 --sample 1 --milestone 10  --mode predict `
ddpm_predict_StockPredict.npy的形状也未改变。请您赐教！

**Comment by Y-debug-sys** [comment]
你好，366是测试集大小，你使用的config里面的序列总长度为24，生成的序列后20个时间点即为预测输出。
