### ISSUE TITLE
Cross-Correlation or Cross-Covariance?

### ISSUE THREAD

**Issue by littlestone111** [Y-debug-sys/Diffusion-TS#14]
Hi, Thanks for updating the codebase frequently.

I am currently working on understanding the correlation score code.  The formula in the paper looks like the Pearson correlation.
<img width="1248" alt="image" src="https://github.com/Y-debug-sys/Diffusion-TS/assets/38016516/a78b73c7-a438-4ce1-aaaf-24ef58e16366">

I also tried the correlation score in the code.
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/38016516/5c2a5626-db8b-42d2-8f93-96f7115f3ec3)

As you can see the first values, it gives 1.17 for feature 1 and feature 1. Should it be 1 instead?  Please let me know If I miss something here.

Thank you so much for your time.

**Comment by Y-debug-sys** [comment]
Hi, the metirc's detailed description can be found in ''Metric on the correlation'' at page 17 in the paper [[Conditional-Sig-Wasserstein-GANs](https://arxiv.org/abs/2006.05421)], and we reuse its [official  code](https://github.com/SigCGANs/Conditional-Sig-Wasserstein-GANs/blob/master/lib/test_metrics.py) . Thanks !

**Comment by littlestone111** [comment]
Thank you for sharing!
