### ISSUE TITLE
metric_tensorflow.ipynb无法运行

### ISSUE THREAD

**Issue by 153201121yf** [Y-debug-sys/Diffusion-TS#15]
您好，我在运行实验的metric_tensorflow.ipynb文件时，提示我当前版本的numpy，需要把numpy.object更换为object,我重新安装了tensorflow，但还是报错，请问要运行这个文件，是需要在require.txt文件的要求之外单独配置环境吗？

**Comment by Y-debug-sys** [comment]
你好，我在进行实验的时候确实使用的是另一个Tensorflow环境。

**Comment by 153201121yf** [comment]
> 你好，我在进行实验的时候确实使用的是另一个Tensorflow环境，不过应该是只需要tqdm和tensorflow的自带包。

谢谢回复，但我这边无法运行，导入包不成功，并提示说numpy版本不对，但其他的代码能正常运行

**Comment by Y-debug-sys** [comment]
是独立的Tensorflow环境吗？Tensorflow与Numpy的版本兼容吗？可以尝试降低Numpy版本。

**Comment by 153201121yf** [comment]
> 是独立的Tensorflow环境吗？Tensorflow与Numpy的版本兼容吗？可以尝试降低Numpy版本。

谢谢回复，我是使用的该项目的虚拟环境（按照require.txt的要求配置的），然后打开jupyter notebook运行的，我尝试了降低numpy版本，但提示我其他包也需降低，并且metric_pytorch.ipynb等也不能正常运行了（不能正常运行的原因是numpy版本太低）

**Comment by Y-debug-sys** [comment]
好的，可以尝试新建环境。我一个可以允许的环境版本如下: tensorflow-gpu==2.10.0, numpy==1.23.4, tqdm==4.65.0。

**Comment by 153201121yf** [comment]
> 好的，可以尝试创建环境。我一个可以运行的环境版本如下：tensorflow-gpu==2.10.0, numpy==1.23.4, tqdm==4.65.0。

谢谢回复，您的意思是重新创建一个虚拟环境是吧，然后额外安装您说的这些包？

**Comment by Y-debug-sys** [comment]
是的，具体请按需求装包。

**Comment by 153201121yf** [comment]
> 是的，具体请按需求装包。

好的，感谢解答
