### ISSUE TITLE
Diffusion Model parameter size

### ISSUE THREAD

**Issue by OmegaAsh** [Y-debug-sys/Diffusion-TS#17]
Hi guys, I am just using this for a project (will be sure to cite). When using the parameter config for the FMRI dataset, I am getting a parameter size of over 13M, but I think in the paper it was around 1.3M. Just wondering if this is an issue that you have encountered, or if it is something that is related to my setup. Thanks,

**Comment by Y-debug-sys** [comment]
Hi, this looks strange. Where did you get the data from? Is it the size of the .pt file?

**Comment by OmegaAsh** [comment]
Hi thanks for the quick reply, I just figured out it was due to my large sequence length, so no issues with the code. Thanks again and I will close this.

**Comment by l402l** [comment]
你好，请问计算model size的函数在哪呢，我计算sine的参数为235249，文中显示的为232177
![1](https://github.com/Y-debug-sys/Diffusion-TS/assets/145762005/ec2388a7-ee7f-4d3c-bcfa-66749fdabb83)

**Comment by Y-debug-sys** [comment]
你好，由于对最初版本代码的调整和可能存在的环境差异，导致模型大小的细微差别很正常。
