### ISSUE TITLE
reproducing the results of Figure 6

### ISSUE THREAD

**Issue by cmzsbql** [Y-debug-sys/Diffusion-TS#18]
Hello. Great research work.
I have some questions about reproducing the results of Figure 6.
1. Do I only need to train the model once to obtain all the results in Figure 6 through inference, or do I need to train different models according to different situations?
2. In the prediction task in Figure 6, do you always keep the history window + prediction window = 48?
3. In code, how do I switch between Diffusion-TS-G and Diffusion-TS-R？
Thanks.

**Comment by Y-debug-sys** [comment]
Hi, for your problems :
1. Yes, of course you can train it just once.
2. Yes, your right.
3. Regarding Diffusion-TS-R, just comment the code in gaussian_diffusion.py like following screeshot
![Comment1](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/8011c154-c646-43df-a662-d4f0e6c3de96)
![Comment2](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/adc616bf-167c-4cb0-8201-f538945e9ea7)

**Comment by cmzsbql** [comment]
Thanks for your reply, my problem is solved.
