### ISSUE TITLE
在代码调试中遇到问题

### ISSUE THREAD

**Issue by GeroRoman** [Y-debug-sys/Diffusion-TS#19]
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/145658421/ae1f0191-31d1-4215-b657-64c19e509f21)
作者您好，我今天在调试代码中遇到这个问题，由于我是深度学习的初学者，请问这个报错是什么意思？该如何修改？

**Comment by Y-debug-sys** [comment]
这是直接运行的main.py，没有指定config文件吗？

**Comment by GeroRoman** [comment]
作者您好，我在参数中作了相应的修改但是没有解决问题
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/145658421/d7eceb8b-2de9-4f8e-a482-23d271109c79)

**Comment by GeroRoman** [comment]
作者您好，我在今天调试的时候发现没有预训练文件，请问这个.pt文件是自己保存的吗？是哪里出了问题吗？
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/145658421/d8fb805b-13c6-4dae-bdfc-51a80a8f33f8)

**Comment by Y-debug-sys** [comment]
是的，需要先训练，不过训练很快，谢谢。
