### ISSUE TITLE
solver 里面trainer的restore

### ISSUE THREAD

**Issue by prettyprettyboy** [Y-debug-sys/Diffusion-TS#2]
restore的返回是不是应该是sample，不然反归一化那儿要出错，还是要把那行注释取消了

**Comment by Y-debug-sys** [comment]
Thanks for pointing it out, it has been fixed.
`samples = trainer.restore(dataloader, [dataset.window, dataset.var_num], coef, stepsize, sampling_steps)`-->`samples, *_ = trainer.restore(dataloader, [dataset.window, dataset.var_num], coef, stepsize, sampling_steps)`
