### ISSUE TITLE
About baselines

### ISSUE THREAD

**Issue by cmzsbql** [Y-debug-sys/Diffusion-TS#23]
Hi,  the implementation of DiffTime is not open source (or maybe I just couldn't find it). I would like to ask you how to reproduce its results.
Thanks.

**Comment by Y-debug-sys** [comment]
It directly uses the network structure of CSDI without hard condition. I mainly optimize its convolutional kernel size and some training parameters such as total training epochs. Thanks!

**Comment by Y-debug-sys** [comment]
It directly uses the network structure of CSDI without hard condition. I mainly optimized its convolutional kernel size and some training parameters such as total training epochs. Thanks!

**Comment by cmzsbql** [comment]
Thanks！
