### ISSUE TITLE
How build_dataloader create {self.name}_ground_truth_{self.window}_test.npy

### ISSUE THREAD

**Issue by cosmo-tw** [Y-debug-sys/Diffusion-TS#25]
Hi,

I am currently working with the preprocessing pipeline in the project, and I need some clarification regarding the steps involved in generating the {self.name}ground_truth{self.window}_test.npy file from the original CSV file. Specifically, I am looking into the real_datasets.py file in the Utils directory but am unsure about the exact preprocessing steps that are applied to the original CSV file from Dataset.

Request:
Could you please provide detailed documentation or comments in the code explaining the preprocessing steps? It would greatly help in understanding the data transformation process and ensure that I can correctly interpret the generated files.

Thank you for your assistance.

**Comment by Y-debug-sys** [comment]
Got it, I'll upload some detailed instructions about data soon.

**Comment by Y-debug-sys** [comment]
See **readme.md** under the *Data* folder for details please. Thanks!

**Comment by cosmo-tw** [comment]
Hi,

Thank you for providing the updated documentation so quickly :)

However, I encountered a dimension error when adding `samples = dataset.scaler.inverse_transform(samples)` at line 93 in `main.py` as suggested.  For context, I am running the command: `python main.py --name exp1 --config_file ./Config/stocks.yaml --gpu 0 --sample 0 --milestone 10` Could you please assist me further with this issue?

```
Traceback (most recent call last):
  File "/signal/Diffusion-TS/main.py", line 98, in <module>
    main()
  File "/signal/Diffusion-TS/main.py", line 93, in main
    samples = dataset.scaler.inverse_transform(samples)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_data.py", line 528, in inverse_transform
    X = check_array(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py", line 893, in check_array
    raise ValueError(
ValueError: Found array with dim 3. None expected <= 2.
```

Thank you!

**Comment by Y-debug-sys** [comment]
Got it, fixed.
