### ISSUE TITLE
Figure 4和Figure 15可视化的问题请教

### ISSUE THREAD

**Issue by hanli997** [Y-debug-sys/Diffusion-TS#26]
作者你好，
非常感谢你提供论文代码，为时序领域发展做出的贡献！
在Figure 4和Figure 15中，你使用TimeGAN作为基线进行可视化：
![图4](https://github.com/Y-debug-sys/Diffusion-TS/assets/152172232/0e5c7455-fe67-4718-90aa-5a48c2fd3010)
![图15](https://github.com/Y-debug-sys/Diffusion-TS/assets/152172232/cfa91bb7-4d3b-4737-a195-f8b63c38e38c)
TimeGAN在数据预处理时会对原始数据进行切片，并把切片随机打乱，变成三维数据ori_data（以默认stock数据集为例，会变成（3661,24,6）），生成的generated_data也是三维数据，
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/152172232/760f648d-5ab8-4ab0-9c23-95744acd6813)
![image](https://github.com/Y-debug-sys/Diffusion-TS/assets/152172232/e65fd8f2-8f8e-428d-89f8-272df10ccecc)
我想请教一下，你在使用TimeGAN时是如何处理得到的generated_data，从而进行Figure 4和Figure 15的可视化？
是否将generated_data还原回原始数据的格式（以默认stock数据集为例，得到对应生成的二维数据（3685,6））?
或者是在generated_data中取出一个切片，和原始数据对应的切片进行对比？

**Comment by Y-debug-sys** [comment]
你好，

1. 首先，TimeGAN训练和生成的时间序列维度全部和本库相同，即分割成（批大小，序列长度，维度大小）；
2. 其次，可视化并没有直接reshape还原回二维数据，实际上数据处理代码（延着时间维度平均）和TimeGAN原始库完全相同；
3. 最后，无条件随机生成切片不存在对应关系。

谢谢！

**Comment by hanli997** [comment]
非常感谢你及时的回复，
我还是有点疑惑，你在使用TimeGAN时是如何处理得到的generated_data，从而进行论文中Figure 15那种的可视化？

**Comment by Y-debug-sys** [comment]
生成完毕后，原封不动（数据范围0-1）保存为numpy文件，之后分别取出原始数据和生成数据绘图。

**Comment by hanli997** [comment]
明白了，感谢你的解答
