### ISSUE TITLE
TypeError: unhashable type: 'list'（Python 3.9）

### ISSUE THREAD

**Issue by GardeniaYANG** [Y-debug-sys/Diffusion-TS#27]
您好，在运行代码的时候，有导包问题，请求解答一下，网上的方式试了遍，没用QAQ

**Comment by Y-debug-sys** [comment]
详细一点的说明？

**Comment by GardeniaYANG** [comment]
from ema_pytorch import EMA
# 这一句的也会报错，不知道什么原因：TypeError: unhashable type: 'list'
&nbsp;


栀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xinyu ***@***.***&gt;; 
发送时间: 2024年6月13日(星期四) 上午10:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27)














 
详细一点的说明？

**Comment by Y-debug-sys** [comment]
能提供运行和报错截图吗？

**Comment by GardeniaYANG** [comment]
栀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Y-debug-sys/Diffusion-TS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 中午12:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27)





 
能提供运行和报错截图吗？

**Comment by Y-debug-sys** [comment]
你好，我无法看到截图，请尝试邮件外的回复方式。。。

![Screen_shot](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/575e51f2-36c5-4872-8c79-c85657383252)

**Comment by GardeniaYANG** [comment]
主要是ema-pytorch的版本兼容问题，我尝试升级一下。QAQ


栀
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Y-debug-sys/Diffusion-TS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27)





 
你好，我无法看到截图，请尝试邮件外的回复方式。。。
 
Screen_shot.png (view on web)

**Comment by gu27-f** [comment]
> 主要是ema-pytorch的版本兼容问题，我尝试升级一下。QAQ 栀 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Y-debug-sys/Diffusion-TS" ***@***.***&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 中午12:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27) 你好，我无法看到截图，请尝试邮件外的回复方式。。。 Screen_shot.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**Comment by gu27-f** [comment]
你好，我也遇到了这个问题，请问你有解决吗

**Comment by gu27-f** [comment]
> 主要是ema-pytorch的版本兼容问题，我尝试升级一下。QAQ 栀 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Y-debug-sys/Diffusion-TS" ***@***.***&gt;; 发送时间:&nbsp;2024年6月13日(星期四) 中午12:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27) 你好，我无法看到截图，请尝试邮件外的回复方式。。。 Screen_shot.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我也遇到了同样的问题。请问你有解决吗

**Comment by Y-debug-sys** [comment]
好的，请问你能够提供截图吗？

**Comment by gu27-f** [comment]
> 好的，请问你能够提供截图吗？
你好，这样可以看到吗
![屏幕截图 2024-06-13 163013](https://github.com/Y-debug-sys/Diffusion-TS/assets/77136868/67ffee6a-eca6-48f2-9c73-ab98aa1d7aec)

**Comment by GardeniaYANG** [comment]
一样的报错，我改了底层代码。

**Comment by gu27-f** [comment]
> 一样的报错，我改了底层代码。

请问，你的现在已经解决了吗

**Comment by Y-debug-sys** [comment]
请问python版本是？我自己换环境重新安装了一遍，依然可以运行

**Comment by Y-debug-sys** [comment]
如果是python 3.9，详见
[问题描述1](https://github.com/lucidrains/muse-maskgit-pytorch/issues/30)
[问题描述2](https://github.com/beartype/beartype/issues/99)

**Comment by gu27-f** [comment]
python是3.9的，可能是我其它的包版本不太对。我重新按照txt换一遍，再试试。谢谢你



---原始邮件---
发件人: "Xinyu ***@***.***&gt;
发送时间: 2024年6月13日(周四) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Y-debug-sys/Diffusion-TS] 导包问题 (Issue #27)




 
好的，请问你能够提供截图吗？

**Comment by GardeniaYANG** [comment]
![X9IW~SIRT6(NA~1A9XNT{ 5](https://github.com/Y-debug-sys/Diffusion-TS/assets/105274811/04b09230-0623-4dd5-b505-9839365e06d6)
作者大大，请问这个报错怎么解呀。这样发图你能看到吗

**Comment by Y-debug-sys** [comment]
请按照 Readme.md 运行 main.py，在终端输入（以 sines 数据集训练为例）：
python main.py --name sine --config_file Config/sines.yaml --gpu 0 --train

**Comment by GardeniaYANG** [comment]
ok，在终端上就没有问题了，谢谢
