### ISSUE TITLE
指标问题咨询

### ISSUE THREAD

**Issue by GardeniaYANG** [Y-debug-sys/Diffusion-TS#29]
您好，我在用用模型生成光伏曲线的时候，用指标测试生成的效果。context-fid非常大，超过100，然后cross correlative非常小，大概是e-8次方级别。您觉得这个可能是什么问题呢？

**Comment by Y-debug-sys** [comment]
你好，数据的信息？比如维度长度。分布可视化情况如何？如果分布曲线没问题的话，或许是TS2Vec模型没学好导致context-fid失效。

**Comment by GardeniaYANG** [comment]
谢谢您的回复，确实是归一化问题
