### ISSUE TITLE
Tutorial0 Unnormalize and Question on FFT term in loss funciton

### ISSUE THREAD

**Issue by littlestone111** [Y-debug-sys/Diffusion-TS#3]
1. The commented code seems to work for datasets other than sine. 
ori_data = np.load(os.path.join(dataset.dir, f"{dataset_name}_norm_truth_{seq_length}_train.npy"))

Maybe there is something with unnormalize_to_zero_to_one?

2. Want to confirm the FFT loss term is utilized for each feature (time series) not each time step.

**Comment by Y-debug-sys** [comment]
For first question, it has been unnormalized to [0, 1] before saving:
![Screen](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/7b79277d-ae39-4c95-aa5a-c2af19c43b37)
And regarding the second question, see the following screenshot：
![Simulate](https://github.com/Y-debug-sys/Diffusion-TS/assets/68762624/d6175c11-bb47-423d-aab3-ebc6a2ff132f)
The output is symmetrical in the second dimension (with length 24). Hope this answer can solve your problem.

**Comment by littlestone111** [comment]
Thank you for the fast reply.

Could you please elaborate a little bit on each dimension of ts_simulate. Is it (Batch, sequence length, # of variable)?

**Comment by Y-debug-sys** [comment]
Yes, the dimension is the same as the input tensor.

**Comment by littlestone111** [comment]
Cool. Thank you for your time.
