### ISSUE TITLE
关于预测数据

### ISSUE THREAD

**Issue by lztlzt-1** [Y-debug-sys/Diffusion-TS#32]
您好，
我最近尝试用训练好的模型进行预测分析
python main.py --name etth --config_file ETTh.yaml --gpu 0 --sample 1 --milestone 10 --mode predict --pred_len 96
他生成了一个矩阵（1732,96,7），但是我不知道该和哪个数据进行对比

**Comment by Y-debug-sys** [comment]
你好，.yaml设置的总长度L是多少？（需要大于96）如果没有改动的话，应该是和OUTPUT文件夹中的samples/etth_norm_truth_{总长度L}_test.npy进行对比的，只比较后面96步，即根据前L-96步生成后96步。可以参考 demo [1](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Tutorial_2.ipynb) 和 [2](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Experiments/solar_nips_forecasting.ipynb).

**Comment by lztlzt-1** [comment]
谢谢，我现在能够查出来数据了，但是我发现这时已经norm过的，如果我想比较没有被norm的数据我需要怎么做呢

**Comment by Y-debug-sys** [comment]
归一化问题参考 [About Data](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Data/readme.md)。

**Comment by lztlzt-1** [comment]
谢谢
