### ISSUE TITLE
对Impution任务进行test时，略微修改denoiser模型，但test结果不变

### ISSUE THREAD

**Issue by breakwa** [Y-debug-sys/Diffusion-TS#34]
作者您好，我先使用如下参数进行模型训练：main.py --train True --sample 1 --mode 'infill'  --milestone 10.
然后使用如下参数进行测试：main.py --train False --sample 1 --mode 'infill'  --milestone 10.
然后打印ddpm_infill_None.npy结果。

接着，我修改了模型 （对etth.yaml中的     n_layer_enc: 3    n_layer_dec: 2 改为  n_layer_enc: 6    n_layer_dec: 4 ，Transformer中forward函数中a, att = self.attn1(self.ln1(x, timestep, label_emb), mask=mask)
        x = x 
        a, att = self.attn2(self.ln1_1(x, timestep), encoder_output, mask=mask)
        x = x
改为
a, att = self.attn1(self.ln1(x, timestep, label_emb), mask=mask)
        x = x + a
        a, att = self.attn2(self.ln1_1(x, timestep), encoder_output, mask=mask)
        x = x+ a ）
然后我重新训练模型，测试模型（参数和配置同修改前）

train的结果是发生了变化，但是修改前后ddpm_infill_None.npy文件的输出一致，test结果没变。请问这是原因呢？以下是ddpm_infill_None.npy的输出(197, 24, 7)的第10个sample的结果（修改前后，图片一致）：
![myplot](https://github.com/Y-debug-sys/Diffusion-TS/assets/41022342/63d2d435-1b06-49bb-a672-38bdba79edbf)

[checkpoint-10 - 修改前.pdf](https://github.com/user-attachments/files/16144003/checkpoint-10.-.pdf)把.pdf改为.pt

[checkpoint-10 - 修改后.pdf](https://github.com/user-attachments/files/16143999/checkpoint-10.-.pdf)把.pdf改为.pt

**Comment by Y-debug-sys** [comment]
你好，我认为是原来的模型已经在训练集过拟合了，加大参数量（似乎放大了3倍）只会加剧这种现象，在测试时无差距。

**Comment by breakwa** [comment]
感谢指点；模型是变化的，最终结果没变的原因应该是denoiser拟合的问题
