### ISSUE TITLE
作者，你好，请问反归一化后的fake.npy和ground_truth_train.npy进行可视化pca与t-sne的结果和未反归一化的结果差距比较大是为什么

### ISSUE THREAD

**Issue by HIUZS** [Y-debug-sys/Diffusion-TS#36]
反归一化的结果可视化
![d47a1b6a7bbf284f79b3cea80120d52](https://github.com/user-attachments/assets/b4517e88-d9a2-49a3-ab2c-b95a4913a5ba)
归一化的结果可视化
![62640f1441d13d62eedf4d7aea7978d](https://github.com/user-attachments/assets/5368fe38-93c3-47c1-b701-6ee9c18e0bb4)

**Comment by Y-debug-sys** [comment]
你好，能提供更多信息吗？我试了stock数据集，反归一化后没有非常大的性能下降。
![stock](https://github.com/user-attachments/assets/f03369e6-ec49-4c4d-89ae-b08001f2d53e)
能给pca截图吗，可以看到数据范围，谢谢。

**Comment by HIUZS** [comment]
未反归一化（fake与norm）
![image](https://github.com/user-attachments/assets/2b9eae4f-b4f0-4d77-b7c1-8ba6ec322d32)
反归一化(fake与ground)
![image](https://github.com/user-attachments/assets/842325a8-a0b7-4f7c-af69-35f4a30c6f67)

**Comment by Y-debug-sys** [comment]
tnse比pca效果差很多，确定是同一批数据吗？

**Comment by HIUZS** [comment]
是的，
![image](https://github.com/user-attachments/assets/0484a909-c995-4b8d-85dd-03f1993d45eb)
![image](https://github.com/user-attachments/assets/9fa8e753-c3ff-4758-ae36-68a9dce72446)
![image](https://github.com/user-attachments/assets/de738bcc-ea93-4c6a-8080-486f156d883b)

**Comment by Y-debug-sys** [comment]
我的猜测是两个原因，如下
1. 数据本身（各个通道的最值）为归一化引入了偏移或者误导
2. 模型没有拟合到位或者出现过拟合

前者可能性或许更大一点。

**Comment by HIUZS** [comment]
好的，谢谢。我有个问题这个曲线中生成数据的曲线一直这种形状，是什么原因
![image](https://github.com/user-attachments/assets/fade3e4a-d0be-4785-8e33-a5b300c5f1bd)

**Comment by Y-debug-sys** [comment]
你是不是把原来的unnormalize_to_zero_to_one注释了

**Comment by HIUZS** [comment]
是的

**Comment by Y-debug-sys** [comment]
你好，请加上

**Comment by HIUZS** [comment]
问题解决了，非常感谢
