### ISSUE TITLE
生成数据与原数据差别比较大

### ISSUE THREAD

**Issue by mkbk-with-circle** [Y-debug-sys/Diffusion-TS#42]
我按照您的步骤执行代码，并且根据Tutorial_0.ipynb中的代码进行作图，发现图像上显示的fake数据与原数据相差过大，想请问会不会是我因为去除了模型中一开始的归一化和后来的去归一化导致的?或者有没有可能是因为yaml上的参数设置问题？
<img width="1313" alt="截屏2024-07-27 16 12 18" src="https://github.com/user-attachments/assets/e04c56e1-8438-4e43-8b0b-6d6592efddc9">

**Comment by mkbk-with-circle** [comment]
增加了max_epoch之后有所改变但是PCA的分布依然是相差极大

**Comment by Y-debug-sys** [comment]
你好，能提供具体修改处吗？可以发我邮箱yxy5315@gmail.com

**Comment by mkbk-with-circle** [comment]
好的，我整理一下发给您的邮箱，太感谢了！

**Comment by mkbk-with-circle** [comment]
已经发送到您的邮箱，如果还有对我的修改处不清楚的地方请您随时问我，感谢！

**Comment by Y-debug-sys** [comment]
找到原因了，虽然取消了数据的归一化，但是在保存至 `my_yaml_ground_truth_100_train.npy` 时却做了反归一化，请取消 __getsamples 中的对应操作，谢谢。

**Comment by mkbk-with-circle** [comment]
好的，感谢！我去把保存数据的那部分代码里的反归一化都去除掉试一试！






发件人：Xinyu Yuan ***@***.***>
发送日期：2024-07-27 17:51:34
收件人：Y-debug-sys/Diffusion-TS ***@***.***>
抄送人："玛卡巴卡" ***@***.***>,Author ***@***.***>
主题：Re: [Y-debug-sys/Diffusion-TS] 生成数据与原数据差别比较大 (Issue #42)

找到原因了，虽然取消了数据的归一化，但是在保存至 my_yaml_ground_truth_100_train.npy 时却做了反归一化，请取消 __getsamples 中的对应操作，谢谢。

**Comment by mkbk-with-circle** [comment]
<img width="1240" alt="截屏2024-07-27 19 21 40" src="https://github.com/user-attachments/assets/c2fef330-a482-4bec-996c-fdf1a45a4793">
q'w请问现在这个算合理的生成数据吗？🤔是不是还有点偏差？以及我是否可以通过增加  n_layer_enc、n_layer_dec等其他参数去改善呢？

**Comment by Y-debug-sys** [comment]
数据维度高（100, 165），数据范围 [0.4, 0.415] 窄，模型太小: Enc层 2, Dec层 2, 嵌入维度 64，精度不够。两条建议：

1. 保留原有的数据归一化操作，扩大数据范围；
2. 改模型参数：Enc层 3, Dec层 3, 嵌入维度 96

**Comment by mkbk-with-circle** [comment]
好！！！无比感谢！

**Comment by mkbk-with-circle** [comment]
我用您的建议修改之后出现了比较奇怪的现象，就是如果我把fake_data.npy的数据与groun_data.npy的数据去对比出来的图片效果改进不佳
<img width="1202" alt="截屏2024-07-27 23 59 04" src="https://github.com/user-attachments/assets/0970543f-8dbf-44dd-b8f7-1a5132ae23c0">
d但是换成把fake_data.npy的数据与norm_data.npy的数据去对比就呈现非常好的图片
<img width="1234" alt="截屏2024-07-28 00 01 22" src="https://github.com/user-attachments/assets/7afc6534-5fe7-4e10-b231-a5df5e3e046e">
我猜测是不是因为我的数据本身数据范围太小的原因呢？

**Comment by Y-debug-sys** [comment]
你好，说明生成没有问题。这是因为 ddpm_fake 保存的是归一化后的数据，对应的是 norm_truth 。见 [About Data](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Data/readme.md)，谢谢。

**Comment by mkbk-with-circle** [comment]
哇哦！！！太感谢啦！！！你是大好人！！祝你事业顺利！！
