### ISSUE TITLE
数据集结构

### ISSUE THREAD

**Issue by HIUZS** [Y-debug-sys/Diffusion-TS#43]
作者，你好。我想改变训练集ground_truth_24_train.npy与无条件生成fake_24_1.npy文件的样本数量，即.npy数据结构中（n,windows，feature）中n的值，该修改config文件中的哪一个参数或代码中的哪条语句

**Comment by Y-debug-sys** [comment]
你好，见

https://github.com/Y-debug-sys/Diffusion-TS/blob/21ca525ed6a0ce4322e05d665c792d2b8dc41f99/main.py#L90

num 为目标采样数，size_ever y为一轮采样数，谢谢！
