### ISSUE TITLE
Size mismatch of model and checkpoint

### ISSUE THREAD

**Issue by fakharehassan** [Y-debug-sys/Diffusion-TS#45]
Hi, 
I have trained the model with the given terminal command, which saves the pre-trained model checkpoints in the respective folder. When I try to run the saved model for sampling, it gives me the following error:

`size mismatch for model.emb.sequential.1.weight: copying a param with shape torch.Size([96, 128, 3]) from checkpoint, the shape in current model is torch.Size([64, 6, 3]).`

Any information on how to resolve this, or if I may be doing something wrong, would be helpful.

**Comment by Y-debug-sys** [comment]
Hi, please check your .yaml filename, it seems that sampling is using the configuration of `sines` dataset.

**Comment by fakharehassan** [comment]
Thanks, I’ll check

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Y-debug-sys** [comment]
Hi, here is an answer from Chat-GPT :

```
import numpy as np
import pandas as pd

# Load the .npy file
data = np.load('input.npy')

# Convert the multi-dimensional array to a two-dimensional array
# Assume we want to flatten each sequence and save it in the CSV file
flattened_data = data.reshape((data.shape[0], -1))

# Save the data to a .csv file
df = pd.DataFrame(flattened_data)
df.to_csv('output.csv', index=False)
```
