### ISSUE TITLE
Generated data distribution seems very different from the original one

### ISSUE THREAD

**Issue by Awenega** [Y-debug-sys/Diffusion-TS#46]
Hi, for my research project, I am trying to use your model to adapt it develop a diffusion model for NILM problem. 
Specifically, through the "Tutorial_0.ipynb" notebook, I trained the model and performed the unconditional data generation and later visualized the pca/t-sne/kernel plots. 
I wanted to ask your opinion regarding the result obtained, which does not seem to be generating correctly. 
The dataset shape is (60000, 128, 1) and below you can see the model configuration.
<img src="https://github.com/user-attachments/assets/3f46c836-4771-4935-b514-8747c52ad498" width=20% height=20%>
<img src="https://github.com/user-attachments/assets/a451c3aa-bf98-4ae2-8dd8-ee752cb2fe54" width=50% height=50%>
<img src="https://github.com/user-attachments/assets/f1fc9f75-30ed-4d47-8e6e-06f287c8c840" width=50% height=50%>
<img src="https://github.com/user-attachments/assets/f277e674-1782-4e65-9076-f6a6b28c4cbf" width=50% height=50%>

I cannot understand the reason why the generated samples seem to have a very different distribution from the original. Would you have any suggestions on how to improve the generation?

**Comment by Y-debug-sys** [comment]
Hi, please use normalized ground truth for Visualizations, which means you should load 'norm_truth.npy' for `ori_data` rather than 'ground_truth.npy'. (See commented code in "Tutorial_0.ipynb" notebook block [4]). Thanks!

**Comment by Awenega** [comment]
Hi, thank you. The ori_data is already equal to the 'norm_truth.npy', which is given by "unnormalize_to_zero_to_one(train_data)" in the "real_dataset.py"

**Comment by Y-debug-sys** [comment]
My point is not about the generated data. Please uncomment the relevant code in "Tutorial_0.ipynb" notebook block [4] and find the corresponding `norm_truth` filename to fill in. It's clear that the range of the real data in your graph is not between 0 and 1, indicating that it is non-normalized data.

![354606085-f277e674-1782-4e65-9076-f6a6b28c4cbf](https://github.com/user-attachments/assets/4a805c0a-889f-4468-a8c8-93d86f9b7c25)

**Comment by Awenega** [comment]
Looking at that image, i thought the same thing. Thank you for confirming my hypothesis. 
I will try to debug the code better, I probably did something wrong during the generation and preprocessing of the original dataset

**Comment by Y-debug-sys** [comment]
See [About Data](https://github.com/Y-debug-sys/Diffusion-TS/tree/main/Data#readme) for instructions of saved files.

**Comment by Awenega** [comment]
Hi, you were right, the original distribution used a different scaler and thus "ruined" the original distribution.

Despite this, however, the new results are not satisfactory....The config used, is the same as before.
 In your experience, what could this be due to?
![pca](https://github.com/user-attachments/assets/2ba27266-9f71-4299-9cac-2991e2b676f1)
![kernel](https://github.com/user-attachments/assets/91bbd51a-007f-47bb-a99e-6a5317fc95fe)

**Comment by Y-debug-sys** [comment]
Hi, it seems that the generated data is normalized for twice .....

Now
![354698028-91bbd51a-007f-47bb-a99e-6a5317fc95fe](https://github.com/user-attachments/assets/8370b0c7-4bbb-4ef2-a36c-c206e04ddd57)
Before
![354606085-f277e674-1782-4e65-9076-f6a6b28c4cbf](https://github.com/user-attachments/assets/14c03a66-1e0b-438e-b2ad-74f09127f8f9)

The original process of `fake_data` is OK. Thanks!

**Comment by Y-debug-sys** [comment]
My email is `yxy5315@gmail.com`. If you have any problems about the code, please let me know!
