### ISSUE TITLE
关于修改您的模型的一些问题

### ISSUE THREAD

**Issue by mkbk-with-circle** [Y-debug-sys/Diffusion-TS#48]
作者大哥您好！我现在在尝试修改您的模型使得我能够通过模型内部的自回归去噪过程生成任意长度的时间序列（但是不是反复用pred模式自回归预测），因此我想问一下，您的模型在学习加噪去噪的过程中，是学习两个相邻时间步之间的加噪去噪，还是学习对一个给定长度下的时间序列的加噪减噪过程呢？如果是前者的话我应该就有可能修改您的sample代码来实现我的目的了，感谢！
<img width="680" alt="截屏2024-08-05 15 16 03" src="https://github.com/user-attachments/assets/c5a96067-6c92-41a2-9678-644df7126edf">

**Comment by Y-debug-sys** [comment]
> 模型在学习加噪去噪的过程中，是学习两个相邻时间步之间的加噪去噪，还是学习对一个给定长度下的时间序列的加噪减噪过程呢？

你好，相邻时间步之间的加噪去噪是通过取样公式实现的，模型降噪后的输出是这个公式里的未知参数。

**Comment by Y-debug-sys** [comment]
取样序列维度由模型的输出维度确定。

**Comment by mkbk-with-circle** [comment]
那您的模型在取样的时候，是直接对一个[batch_size, time_step, feature_size]的一个序列**整体**进行取样是吗，还是一个一个时间步的取样？或者我换个问法，我理解的扩散模型最后生成一个时间序列的步骤就是不断地在前一个时间步上去噪，从而生成后一个时间步，并且重复这个行为，请问您的模型是这样的嘛？

**Comment by Y-debug-sys** [comment]
你好，是整体非自回归生成。

**Comment by mkbk-with-circle** [comment]
好的感谢！
