### ISSUE TITLE
Regarding the generation of datasets with varying time spans

### ISSUE THREAD

**Issue by mjbooo** [Y-debug-sys/Diffusion-TS#50]
Hi! First of all, thank you for your excellent work and the great implementation! Thanks to your reproducible and well-structured codebase, I was able to apply your model to various custom datasets.

I have a question about generating time sequences with Diffusion-TS. From my understanding, Diffusion-TS assumes that the dataset is evenly timestamped.

However, in some datasets, time spans can vary, and my question is about generating data that includes timestamps with Diffusion-TS in such cases. An easy and intuitive way to handle this would be to create a specific column indicating unevenly stamped time values. However, in this case, Diffusion-TS doesn't ensure that the time column will be monotonically increasing, even though it does capture the general tendency of increasing.

So, how can I ensure that a column is monotonically increasing? As the primary author who understands your work best, do you have any better ideas for handling this kind of dataset?

Here is an example of the dataset I mentioned:

| time | feature1 | feature2 | ... |
|------|----------|----------|-----|
| 0    | xx       | yy       | ... |
| 3    | xx       | yy       | ... |
| 4    | xx       | yy       | ... |
| 4    | xx       | yy       | ... |
| 7    | xx       | yy       | ... |
| 8    | xx       | yy       | ... |
| 8    | xx       | yy       | ... |
| 9    | xx       | yy       | ... |
...

**Comment by Y-debug-sys** [comment]
Hi, what does the `time` column mean? Why do the same values appear?

**Comment by mjbooo** [comment]
Oh, it's because sometimes multiple rows or observations can occur simultaneously.
There’s a bit of a long story, but you can just focus on the property of the time column being monotonically increasing.

**Comment by Y-debug-sys** [comment]
Hi, I don't think this is a good idea to add a column. Given a missing indicator mask, you can 

1. impute the missing values in the initial value using the sample mean (It's simple);
2. or pretrain a [autoencoder](https://dl.acm.org/doi/10.5555/3326943.3327090) by only reconstructing the known part to get a resonable estimation of the missing part.

Then input the pre-processed data into our model. And there are two suggestions:

1. disable fourier loss as the series is irregular, you can find `use_ff` in
https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Models/interpretable_diffusion/gaussian_diffusion.py#L35C1-L57C7
2. also only reconstructing known part to mitiget the impact of estimated values.

Thanks!
