### ISSUE TITLE
一些关于代码的问题

### ISSUE THREAD

**Issue by annis234** [Y-debug-sys/Diffusion-TS#51]
作者您好！非常欣赏您的工作！我有一个问题。
训练时候没有看到验证集，那直接设置如18000步训练epoch会不会难以监测到过拟合的问题呢？
![image](https://github.com/user-attachments/assets/a169bea3-77b2-4217-83bc-44da961d9bac)

如上图我使用了etth数据以及原始的config，它在10000步甚至之前train loss看上去已经收敛了，但是因为没有validation loss，所以难以判断有没有过拟合和之后继续训练会不会过拟合。想提问作者在使用时是如何保证没有过拟合的呢

**Comment by annis234** [comment]
![image](https://github.com/user-attachments/assets/c6f6c666-a054-4753-8cdc-8b8675314aff)
我还想询问一下这里sample为什么要循环num_cycle次

**Comment by Y-debug-sys** [comment]
> 因为没有validation loss，所以难以判断有没有过拟合和之后继续训练会不会过拟合。想提问作者在使用时是如何保证没有过拟合的呢

你好，无条件生成任务没有测试集的概念，所以过拟合影响不大。此外，预测和填补可以加入dropout减少过拟合的概率，当然你也可以加入earlystoping分割验证集比较FID或其它指标来早停。

>我还想询问一下这里sample为什么要循环num_cycle次

由于取样过程开销大，需要把大量取样分割成多次少量取样来降低开销。
