### ISSUE TITLE
生成ddpm_fake.npy与train_ground.npy相差过大

### ISSUE THREAD

**Issue by HIUZS** [Y-debug-sys/Diffusion-TS#52]
作者，您好。我对您的代码做了少许改动，无条件生成后进行可视化发现生成ddpm_fake.npy与train_ground.npy相差过大（已经进行了反归一化）
我的train_ground.npy结构为（34826,129,2）ddpm_fake.npy结构为（200000,129,2）
![Uploading 归一化1.png…]()
![Uploading 归一化图片.png…]()

**Comment by HIUZS** [comment]
这是反归一化的设置
![归一化1](https://github.com/user-attachments/assets/46903400-c082-48ba-b136-fb0749bfa4b6)
![归一化图片](https://github.com/user-attachments/assets/ee0839a0-3336-4044-b98f-bf90ef2e81c0)
这是无条件生成后进行可视化发现生成ddpm_fake.npy与train_ground.npy
![image](https://github.com/user-attachments/assets/2c7a190f-72a1-4363-b928-3b36f26e71c5)
![image](https://github.com/user-attachments/assets/a42c9f7d-6022-4536-a24a-41b89bb3e84c)

**Comment by HIUZS** [comment]
![image](https://github.com/user-attachments/assets/93f52ecd-cfe6-4516-8321-680a91c14083)

**Comment by Y-debug-sys** [comment]
你好，能看看归一化后的密度图吗，只需要真实数据的分布。

**Comment by Y-debug-sys** [comment]
试试取消 autonorm，不要把数据展开到[-1,1]（.yaml 中 `neg_one_to_one` 的设置为false），再训练一次。

**Comment by HIUZS** [comment]
> 试试取消 autonorm，不要把数据展开到 [-1,1]（.yaml 中的 `neg_one_to_one` 设置为 False），再训练一次。

好的，我试验一下

> 你好，能看看归一化后的密度图吗，只需要真实数据的分布。
其中红色的线为真实数据归一化后的密度图
![image](https://github.com/user-attachments/assets/8e1f5b66-aedc-4c0d-9c68-b4eb0bde1dd6)

**Comment by HIUZS** [comment]
作者，您好。这是在您的建议之下射程的结果，但结果解雇依然不是很理想，下面是ground.npy与fake.npy的可视化。
我猜想有几个原因会造成这种现象
1、csv文件的数据过于庞大，造成生成效果不达标
2、配置文件修改错误
3、修改原始代码导至错误
能否根据您的经验来帮助我完成修改
![image](https://github.com/user-attachments/assets/58c1c466-152a-4b93-89cd-ad818c78e7b4)
![image](https://github.com/user-attachments/assets/eccfffcd-1549-49f9-a5c7-447f570ef1f4)
![image](https://github.com/user-attachments/assets/721709ac-c9f7-4bf8-acdc-b00b92e92dc3)

**Comment by Y-debug-sys** [comment]
好的，相关代码发我邮箱 yxy5315@gmail.com 吧。

**Comment by HIUZS** [comment]
好的，多谢您

**Comment by HIUZS** [comment]
作者，您好。下午我用了其中一小段进行生成，修改代码和下午运行的结果已经发您邮箱了。请您有时间解答一下

**Comment by Y-debug-sys** [comment]
![output](https://github.com/user-attachments/assets/791355b1-2622-4c25-a645-9166109720cd)
![output1](https://github.com/user-attachments/assets/f094d0f8-4a2b-4985-9a99-b106b0b22051)
![output3](https://github.com/user-attachments/assets/53183ebc-edf6-4361-b49c-3ae6d8141282)
