### ISSUE TITLE
关于条件生成时间序列，数据格式的问题

### ISSUE THREAD

**Issue by holydick99** [Y-debug-sys/Diffusion-TS#53]
感谢作者对模型的开源，我有一个问题，当前我的数据集是（样本数，时间长度），同时数据有0，1两种标签，那我的csv数据格式应该是什么样，才能符号模型的输入才能使用标签去引导数据的生成

**Comment by Y-debug-sys** [comment]
你好，请问任务是什么？按类别生成吗？

**Comment by Y-debug-sys** [comment]
见 [回答](https://github.com/Y-debug-sys/Diffusion-TS/issues/40#issuecomment-2242586716)，谢谢。

**Comment by holydick99** [comment]
> 见 [回答](https://github.com/Y-debug-sys/Diffusion-TS/issues/40#issuecomment-2242586716)，谢谢。

我的理解如下，如果我的数据集里面有N个样本，但是只有A和B两种，如果生成A和B两种数据的话，我只需要分别传入一个A类数据和一个B类数据？

**Comment by Y-debug-sys** [comment]
不是，可以照常一起不分类训练，只在生成的时候像我们一样导向，只不过需要额外训练一个分类器，见 [Classifier-guidance 源码](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/guided_diffusion.py).

**Comment by holydick99** [comment]
感觉有点混乱，所以我还是直接传入一个n×时间步长的数据即可，但是要在代码中修改配置即在代码中添一个分类器训练？？

**Comment by Y-debug-sys** [comment]
> 直接传入一个n×时间步长的数据即可

是的，不需要分类训练，但是需要额外训练一个辨别器（输入加噪的xt后判断类别），取样时，按照辨别器的输出（向着指定类别梯度下降）调整生成结果。

**Comment by holydick99** [comment]
![XOX$2@3EFT`27VHBTD@Z_S9](https://github.com/user-attachments/assets/9204dd67-6f8f-4e0d-b24b-d09d3da9fccd)
意味着我要去修改这个代码来符合我的数据集，然后添加到项目代码中。我参考了你上面引用的代码，但是发现在guided_diffusion.py和项目中的采样函数并不相似，所以对一个新手来说可能并不知道这个修改的思路一个如何去建立。还是说只需要将下面这段代码并入到您的采样函数中
![Uploading image.png…]()

我还有一个问题，如果我想采用非条件生成，是否意味着我传入同一类数据（n，时间长度）即可生成相同类？

**Comment by holydick99** [comment]
第二张图如图
![image](https://github.com/user-attachments/assets/3741ffba-72bc-4dbf-9fc1-2d679f9e3072)

**Comment by Y-debug-sys** [comment]
你好，是差不太多的，画圈的部分可以直接加入原代码（替换 [langevin_fn]( https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Models/interpretable_diffusion/gaussian_diffusion.py#L359) 中的infill_loss）

![image](https://github.com/user-attachments/assets/2bcec276-c1dc-45bf-9165-1e2bdf41c281)

**Comment by holydick99** [comment]
> 你好，是差不太多的，画圈的部分可以直接加入原代码（替换 [langevin_fn](https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Models/interpretable_diffusion/gaussian_diffusion.py#L359) 中的 infill_loss ）
> 
> ![image](https://private-user-images.githubusercontent.com/68762624/362569272-2bcec276-c1dc-45bf-9165-1e2bdf41c281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTg4NjAsIm5iZiI6MTcyNDkxODU2MCwicGF0aCI6Ii82ODc2MjYyNC8zNjI1NjkyNzItMmJjZWMyNzYtYzFkYy00NWJmLTkxNjUtMWUyYmRmNDFjMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4MDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjk1ZjMwOTRkMjYwOWJlOGVjMmFkMTFjNjdhNTYwYjdjYzA4MTNhNmFmMTU4OTljYjZjY2ZiMGUzZTAwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ed3Dtez1f2IcJ8rV6U53uT9Cqu1CVVPhSM8HdRR9Yik)

我还有一个问题，是否意味着我传入同一类数据（n，时间长度）即可生成相同类？以及我如何确定，我数据的feature-size，在运行过程中出现了
Traceback (most recent call last):
  File "main.py", line 98, in <module>
    main()
  File "main.py", line 76, in main
    trainer.train()
  File "G:\Diffusion-TS-test\engine\solver.py", line 89, in train
    loss = self.model(data, target=data)
  File "I:\anaconda\envs\dts\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\Diffusion-TS-test\Models\interpretable_diffusion\gaussian_diffusion.py", line 264, in forward
    assert n == feature_size, f'number of variable must be {feature_size}'
AssertionError: number of variable must be 2
的报错

**Comment by holydick99** [comment]
> 你好，是差不太多的，画圈的部分可以直接加入原代码（替换 [langevin_fn](https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Models/interpretable_diffusion/gaussian_diffusion.py#L359) 中的 infill_loss ）
> 
> ![image](https://private-user-images.githubusercontent.com/68762624/362569272-2bcec276-c1dc-45bf-9165-1e2bdf41c281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTg4NjAsIm5iZiI6MTcyNDkxODU2MCwicGF0aCI6Ii82ODc2MjYyNC8zNjI1NjkyNzItMmJjZWMyNzYtYzFkYy00NWJmLTkxNjUtMWUyYmRmNDFjMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA4MDI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNjk1ZjMwOTRkMjYwOWJlOGVjMmFkMTFjNjdhNTYwYjdjYzA4MTNhNmFmMTU4OTljYjZjY2ZiMGUzZTAwZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ed3Dtez1f2IcJ8rV6U53uT9Cqu1CVVPhSM8HdRR9Yik)

- 我还有一个问题，是否意味着我传入同一类数据（n，时间长度）即可生成相同类？
- 在只输入数据这种情况下条件和非条件生成的区别是什么？
- 同时想请问一下有如何根据自己的data确定config中参数的配置的讲解吗？

**Comment by Y-debug-sys** [comment]
1. 与原本的插入预测不同，分类生成不需要传入任何数据，只需要传入额外的分类器和所需生成的类。
2. 模型本体训练无区别，生成加了导向，速度会慢一点。
3. 只需要改动对应的数据维度和序列长度即可运行。

**Comment by holydick99** [comment]
> 1. 与原本的插入预测不同，分类生成不需要传入任何数据，只需要传入额外的分类器和所需生成的类。
> 2. 模型本体训练无区别，生成加了导向，速度会慢一点。
> 3. 只需要改动对应的数据维度和序列长度即可运行，剩下的属于调参选项。

我想您对我的问题可能有点误解，首先我输入我的A类数据进行训练diffusion-model，然后我在您提供的选项种选择采样条件
![L(_E}BZDG$WJ2J41P1@AVIP](https://github.com/user-attachments/assets/6f88dd37-dd33-4c80-973b-6ee0f5533a00)
，后生成一定数量的A类数据。这样是可行的吗？

我对您之前的解答的理解是，我传入包含N类的数据，此时diffusion学习到了N类的噪声分布，在生成时我只需要输入固定类即可生成对应数据，但是我对分类器的作用仍然有一些困惑？

**Comment by Y-debug-sys** [comment]
你好，是可以的，谢谢。

**Comment by holydick99** [comment]
> 你好，是可以的，谢谢。

谢谢解答

**Comment by hong611** [comment]
您好，请问分类生成不需要传入任何数据是什么意思，那模型怎么训练和测试呢

**Comment by Y-debug-sys** [comment]
> 您好，请问分类生成不需要传入任何数据是什么意思，那模型怎么训练和测试呢

你好，见 https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Experiments/eeg_multiple_classes.ipynb ，意思是只需要一个额外的分类器。

**Comment by hong611** [comment]
如果我想在第一层将时序分成2n个窗口做注意力，第二层分成n个窗口做注意力，第三层做全局注意力，请问应该修改哪部分代码呢
