### ISSUE TITLE
生成后效果与初始数据很不相关，关于参数设置的改正

### ISSUE THREAD

**Issue by holydick99** [Y-debug-sys/Diffusion-TS#55]
![@3%%X{%SEENZ{OB4SZO Y{8](https://github.com/user-attachments/assets/d431b7e4-f15c-4473-9935-a7ac67c1d64c)
![_ ~P0Z3I1~EX3AY2A QZ(7U](https://github.com/user-attachments/assets/1b038b49-5035-4279-b65b-85a96e172749)
![DW%3NW1EBN (9G3HXQ4_26S](https://github.com/user-attachments/assets/b4a410b7-b7e2-4e1c-935f-8a5f11c0e855)
图中可以发现，在使用模型生成后，效果很差。我认为可能是参数设置错误的原因。阐述一下流程：输入数据（样本数，时间间长度），但是在训练配置中我的feature_size必须要与时间长度相等才可以进行训练，通过观察fmri数据集维度为（10000，5）个人觉得输入数据是否应该改为（时间长度，样本数）？

**Comment by Y-debug-sys** [comment]
归一化问题，请使用归一化原始数据比较，取消Jupter notebook对norm_truth的注释，谢谢！

**Comment by holydick99** [comment]
![TR4XILM{QJ6CL$9RL4L06G6](https://github.com/user-attachments/assets/1d198d80-d401-47a1-afb4-c30116ad719b)
xi谢谢解答，但是似乎您的代码中并没有对应被注释项

**Comment by Y-debug-sys** [comment]
[13] 块对 ori_data 的注释取消，只有示范的 sine 数据集使用 ground_truth。

**Comment by Y-debug-sys** [comment]
发一下密度图和改动处。

**Comment by holydick99** [comment]
> 发一下密度图和改动处。

密度图是？，改动是发配置文件中的改动除吗

**Comment by Y-debug-sys** [comment]
最上面的第三个图

**Comment by Y-debug-sys** [comment]
> max_epochs: 10
results_folder: ./Checkpoints_EEG
gradient_accumulate_every: 2
save_cycle: 1 # max_epochs // 10

请把 max_epochs 和 save_cycle 放大，这里的 epoch 指的是一次梯度优化，不是循环数据集一轮，如果是如图所示的 2000 个数据，建议分别定为10000和1000，此外下列项也改动一下：

patience: 3000 --> 2000

**Comment by Y-debug-sys** [comment]
期待结果，以前我也做过 eeg 分类生成的工作，效果应该是没有问题的。

**Comment by holydick99** [comment]
> > max_epochs: 10
> > results_folder: ./Checkpoints_EEG
> > gradient_accumulate_every: 2
> > save_cycle: 1 # max_epochs // 10
> 
> 请把 max_epochs 和 save_cycle 放大，这里的 epoch 指的是一次梯度优化，不是循环数据集一轮，如果是如图所示的 2000 个数据，建议分别定为10000和1000，此外下列项也改动一下：
> 
> patience: 3000 --> 2000

![BURI`1 L1XQFU0WNB9`_JQC](https://github.com/user-attachments/assets/86ab4037-9686-4815-89ae-c6f2c683d6a5)
- 似乎我的配置与你的配置差别不算很大，只有patience有区别
- 我还是比较怀疑是传入数据形状的错误，请问一下您当时做eeg工作时是如何传入数据的？
- 还有，我这里传入的eeg数据是由多通道数据卷积后提取出的特征，这个会与表现差有关吗？
- 我的数据描述：初始数据（样本数，通道数，时间步长）--卷积-->（样本数，特征长度）。
- 当我传入（2946，16）这个数据维度时我认为feature-size应该为2946？就像最后生成的数据那样，seq-lenth为什么会等于window-size

**Comment by Y-debug-sys** [comment]
信息太少，改动的几个文件和数据发我邮箱吧 *yxy5315@gmail* 。

**Comment by holydick99** [comment]
> 信息太少，改动的几个文件和数据发我邮箱吧 _yxy5315@gmail_ 。
邮件已经发送，感谢你的帮助

**Comment by Y-debug-sys** [comment]
![image](https://github.com/user-attachments/assets/31eab26f-96b5-43f8-bb6b-abd47a2c11c8)
