### ISSUE TITLE
About multi-channel data generate

### ISSUE THREAD

**Issue by holydick99** [Y-debug-sys/Diffusion-TS#57]
The model is capable of generating data with multiple channels. If this is the case, what should the input training data resemble?（n-samples, n-channels, time-steps）

**Comment by Y-debug-sys** [comment]
Hi, it should be (n-samples, time-steps, n-channels). Thanks!

**Comment by holydick99** [comment]
> Hi, it should be (n-samples, time-steps, n-channels). Thanks!

thanks！

**Comment by holydick99** [comment]
another question if I wanna generate one type data, the input training data should be (n-sample, time-steps) right?, but I can't understand the windows why must equal to serie-length, and what feature-size mean

![5{P7_STDDV6~2XD$_IP8XY](https://github.com/user-attachments/assets/81c39a3f-f17f-4529-839f-180cb85192f7)
![L{3$F7SXXWBT BITT@6@`R4](https://github.com/user-attachments/assets/06451a37-25b5-4a9a-b3d8-cbd2c5fdf2d9)

**Comment by holydick99** [comment]
if I have one dataset (n-sample, time-steps) ->(128, 16) the seq-length should be 16, but the feature-size must = 16 can running code

**Comment by Y-debug-sys** [comment]
In fact, the size of your dataset is (n-sample, time-steps, 1).
