### ISSUE TITLE
IndexError: index 2047 is out of bounds for axis 0 with size 1739

### ISSUE THREAD

**Issue by lllzzz3** [Y-debug-sys/Diffusion-TS#59]
<img width="728" alt="719b379be4156227f0061987da3e88b" src="https://github.com/user-attachments/assets/ce692b48-de2e-416f-a804-fe847900fb96">

![Uploading e85a4b4bddba449def080c645362ed5.png…]()

**Comment by Y-debug-sys** [comment]
Hi, etth_norm_truth_train --＞ etth_norm_truth_test.

**Comment by lllzzz3** [comment]
ok，thanks
