### ISSUE TITLE
About conditional time series forecasting

### ISSUE THREAD

**Issue by whyywh** [Y-debug-sys/Diffusion-TS#60]
Thank you to the author for open-sourcing this model. I have a question: What are the conditions for conditional generation mentioned in the paper? Are other covariates and sequences input into the network together? I didn't see this part while going through the code.

**Comment by Y-debug-sys** [comment]
Hi, the related codes are listed as follows:

1. Load conditions (masked time series) for inference :

https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Utils/Data_utils/real_datasets.py#L160C5-L164C68

2. Inference (conditions are transmited as `target` param):

https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/engine/solver.py#L142C4-L164C70

Thanks!

**Comment by whyywh** [comment]
OK! Thanks for your reply, best wishes！
