### ISSUE TITLE
生成数据与原始数据的对应关系

### ISSUE THREAD

**Issue by hanli997** [Y-debug-sys/Diffusion-TS#62]
作者你好，我的问题是关于生成数据和原始数据的对应关系，问题可能有些低级，还请您不吝赐教，万分感谢！
默认参数，以stocks数据集为例，建立的dataset是(3662,24,6)，即3662个(24,6)的片段；经过训练和采样后得到生成数据ddpm_fake_stock的shape=(4002,24,6)即4002个(24,6)片段。
1.生成数据和原始数据是否有对应关系？
即我是否可以从truth_train中取出一个原始片段，然后再从ddpm_fake中也取出它所对应的生成片段，这两个片段是高度相关联的，可以直接进行对比？
还是说，生成的ddpm_fake和原始的truth_train没有对应关系，生成的片段是基于模型所学到的整体原始数据的分布，而不是从具体的单个样本得到的？
2.如果没有对应关系，那么我想要实现生成与具体片段直接对应的序列，您有什么好的建议吗？

**Comment by Y-debug-sys** [comment]
你好，对应关系指的是趋势或者周期相同？还是说只是先对原始数据加噪到高斯再反向去噪重构得到新的样本？

**Comment by hanli997** [comment]
对应关系是指：
打个不恰当的比方，一张cat_real图片，生成得到一张cat_fake图片；一张dog_real图片，生成得到一张dog_fake图片，那么就可以拿cat_fake和cat_real放在一起对比，而不能拿cat_fake和dog_real放在一起对比。
stocks原始数据(3662,24,6)，假设是3662个“real图片”，模型生成得到(4002,24,6)，即4002个”fake图片”，假设有对应关系，那么可以从原始数据(3662,24,6) “real图片”中取出一个，然后再从生成数据(4002,24,6)”fake图片”中取出它所对应的生成的一个，两个可以放在一起比较。
就像从下图的原始数据中取出一个“片段1”，然后再从生成数据中取出它所对应的“生成片段1”，两个就可以放在一起比较，而不能把原始数据中的“片段2”和“生成片段1”对比
![image](https://github.com/user-attachments/assets/9483943e-de37-46ef-b9c6-b1be46099ed0)

**Comment by Y-debug-sys** [comment]
所以相似的标准是什么？某些片段相同？峰值相同？亦或是曲线的变化区间相同？

**Comment by hanli997** [comment]
对应标准是两个片段“相似”，就像上图中原始“片段1“和”生成片段1“，它们的数据变化、值的范围、特征间关系是“相似”的，而原始“片段2”和“生成片段1”则不相似。
假设用stocks二维数据original(3685,6)，滑动窗口后dataset(3662,24,6)，dataset按照切片方式是可以还原回原始的original(3685,6)，如果原始片段和生成片段有对应关系，那么同样生成的generated(4002,24,6)也可按照对应关系，恢复成generated(3685,6)。
这里我的关注点是直观上的看待原始数据与生成数据

**Comment by Y-debug-sys** [comment]
如果只是追求与原始片段 x 直观上类似，只需要前向加噪 x 到某个 xt（比如一共1000步，加到800步以保留一些可辨识的信息），再以 xt 为起点一步步去噪到 x0，此时 x0 即认为是类似于 x 的序列。如果按照库中的条件生成方法，必须显式地给出生成片段 x0 与原始片段 x 的关系。谢谢！

**Comment by hanli997** [comment]
非常感谢您耐心的解答，我很有收获，期待您在学术上产出更加优秀的作品！
