### ISSUE TITLE
about feature size

### ISSUE THREAD

**Issue by holydick99** [Y-debug-sys/Diffusion-TS#63]
In config.yaml file there is a "feature_size" I don't know this depend on wlich feature of data. My data shape is (samples, seq_length) = (10000,178), Looking for your reply

**Comment by Y-debug-sys** [comment]
In fact, your size is  (10000,178, 1), which means you need first expand your tensor at the last dim, then set feature_size=1 in the config.yaml. Thanks!

**Comment by holydick99** [comment]
> Hi, holydick99. In fact, your size is (10000,178, 1), which means you need first expand your tensor at the last dim, then set feature_size=1 in the config.yaml. Thanks!

Thanks for your answer!

**Comment by holydick99** [comment]
> Hi, holydick99. In fact, your size is (10000,178, 1), which means you need first expand your tensor at the last dim, then set feature_size=1 in the config.yaml. Thanks!

where should this step be added, at beginning my data shape is (1w, 1, 178) but ERROR about this: 
/Diffusion-TS-test/Utils/Data_utils/real_datasets.py:218, in EpilepsyDataset.read_data(filepath, name)
    215 """Reads a single .csv
    216 """
    217 data = io.loadmat(filepath + '/pseudo_labels_epilepsy.mat')['Epilepsy']
    219 scaler = MinMaxScaler()
    220 scaler = scaler.fit(data)
except dim <= 2

So, you mean after data scaler then add dim?

**Comment by Y-debug-sys** [comment]
Hi, please expand your data after Minmax Normalization. The scaler only support a shape like (x, y) or (x, ).

**Comment by holydick99** [comment]
> Hi, please expand your data after Minmax Normalization. The scaler only support a shape like (x, y) or (x, ).
![1061730295053_ pic](https://github.com/user-attachments/assets/33d7bcd8-5329-41cf-ad4e-90bd77f1c9ef)

hi, data and scaler both should be expand？ or just data

**Comment by Y-debug-sys** [comment]
Sorry, I have corrected the answer.

**Comment by Y-debug-sys** [comment]
Then you can normalize the ground truth by `data_norm = scaler.transform(data.reshape(-1,1)).reshape(data.shape)` and obtain your unnormalized generation by `gen = scaler.transform(gen.reshape(-1,1)).reshape(gen.shape)`

**Comment by holydick99** [comment]
> Then you can normalize the ground truth by `data_norm = scaler.transform(data.reshape(-1,1)).reshape(data.shape)` and obtain your unnormalized generation by `gen = scaler.inverse_transform(gen.reshape(-1,1)).reshape(gen.shape)`

these two lines code are little confused me. 
First, I'm curious about how to set feature-size. 
And my data in dataset is (samples, 1 ,seq_length), before I scaler it I use sequeeze to fit. 
What's more, only if I set the feature-size = seq_length the model can be trained. 
So there is any problem with my step? Or you can corrected my step! thank you.

**Comment by Y-debug-sys** [comment]
I think you should refer to [mujoco_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/mujoco_dataset.py) and [sine_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/sine_dataset.py) more. The only difference is the part of loading data. The only difference is in the data extraction part; the other two directly synthesis data with dimensions (num_samples, seq_length, feature_size).

**Comment by holydick99** [comment]
> I think you should refer to [mujoco_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/mujoco_dataset.py) and [sine_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/sine_dataset.py) more. The only difference is the part of loading data; the other two directly synthesis data with dimensions (num_samples, seq_length, feature_size).

OK, thanks for your reply!
