### ISSUE TITLE
About conditional diffusion

### ISSUE THREAD

**Issue by HxSun08** [Y-debug-sys/Diffusion-TS#64]
Thank you for adding such a great repository! It’s really helpful. 

I’d like to ask if your code includes any conditional diffusion elements—for instance, generating time series data with a one-hot label. If not, could you provide some advice on where to start implementing this?

Thanks so much!

**Comment by Y-debug-sys** [comment]
Hi, all you need is [Classifier Guidance](https://arxiv.org/abs/2105.05233) or  [Classifier-Free Guidance](https://arxiv.org/abs/2207.12598) . Regarding Classifier Guidance, you can train an additional classifier (x_t->label) to guide the reverse process, and the related code of Classifier-Free Guidance can be found in [classifier_free_guidance](https://github.com/lucidrains/denoising-diffusion-pytorch/blob/main/denoising_diffusion_pytorch/classifier_free_guidance.py).

**Comment by HxSun08** [comment]
Thank you for your prompt reply and recommendation! I’d like to ask if your code provides an interface for the classifier. If not, could you suggest where it would be best to add the implementation? Thanks!

**Comment by Y-debug-sys** [comment]
Sorry, I don’t have any interface to provide. You might not necessarily need a classifier if you use another method ([Classifier-Free Guidance](https://arxiv.org/abs/2207.12598)). I’ll try to upload code related to classification in the future.
