### ISSUE TITLE
About __getsamples function in Diffusion-TS-test/Utils/Data_utils/real_datasets.py 

### ISSUE THREAD

**Issue by holydick99** [Y-debug-sys/Diffusion-TS#65]
Hi, I have change code according to my dataset. But there is a ERROR confused me, ERROR show as below:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)

File ~/Diffusion-TS-test/Utils/Data_utils/real_datasets.py:49, in CustomDataset.__init__(self, name, data_root, window, dim, proportion, save2npy, neg_one_to_one, seed, period, output_dir, predict_length, missing_ratio, style, distribution, mean_mask_length)
     46 self.auto_norm = neg_one_to_one
     48 self.data = self.__normalize(self.rawdata)
---> 49 train, inference = self.__getsamples(self.data, proportion, seed)
     51 self.samples = train if period == 'train' else inference
     52 if period == 'test':

File ~/Diffusion-TS-test/Utils/Data_utils/real_datasets.py:71, in CustomDataset.__getsamples(self, data, proportion, seed)
     69     print(data.shape)
     70     print(data[start:end, :].shape)
---> 71     x[i, :, :] = data[start:end, :]
     73 train_data, test_data = self.divide(x, proportion, seed)
     75 if self.save2npy:

ValueError: could not broadcast input array from shape (178,178) into shape (178,1)
-----------------------------------------------------------------------------------

My original data.shape is (n_samples, channel = 1, time_steps = 178), so I change my code to MinMaxScaler successfully:
------------------------------------------------------------------------------
class EpilepsyDataset(CustomDataset):
    def __init__(
        self,
        proportion=1.,
        **kwargs
    ):
        super().__init__(proportion=proportion, **kwargs)

    @staticmethod
    def read_data(filepath, name=''):
        """Reads a single .csv
        """
        data = io.loadmat(filepath + '/pseudo_labels_epilepsy.mat')['Epilepsy']
        print(data.shape)
        data = data.squeeze(axis=1)
        print(data.shape) = (n_samples,178)
        scaler = MinMaxScaler()
        scaler = scaler.fit(data)
        # data = np.expand_dims(data,axis =-1)
        # print(data.shape)
        
        return data, scaler
--------------------------------------------------------------------------
And you mentioned my dataset use to train should be (n_samples, time_steps = 178, feature_size = 1) so I changed self.var_num = 1 to reshape data, but when run my code there is a error I show like before:
class CustomDataset(Dataset):
    def __init__(
        self, 
        name,
        data_root, 
        window=178, 
        dim = 1,
        proportion=0.8, 
        save2npy=True, 
        neg_one_to_one=True,
        seed=123,
        period='train',
        output_dir='./OUTPUT',
        predict_length=None,
        missing_ratio=None,
        style='separate', 
        distribution='geometric', 
        mean_mask_length=3
    ):
        super(CustomDataset, self).__init__()
        assert period in ['train', 'test'], 'period must be train or test.'
        if period == 'train':
            assert ~(predict_length is not None or missing_ratio is not None), ''
        self.name, self.pred_len, self.missing_ratio = name, predict_length, missing_ratio
        self.style, self.distribution, self.mean_mask_length = style, distribution, mean_mask_length
        self.rawdata, self.scaler = self.read_data(data_root, self.name)
        self.dir = os.path.join(output_dir, 'samples')
        os.makedirs(self.dir, exist_ok=True)

        self.window, self.period = window, period

        _**self.len, self.var_num = self.rawdata.shape[0], dim**_

        self.sample_num_total = max(self.len - self.window + 1, 0)
        self.save2npy = save2npy
        self.auto_norm = neg_one_to_one

        self.data = self.__normalize(self.rawdata)
        train, inference = self.__getsamples(self.data, proportion, seed)

        self.samples = train if period == 'train' else inference
        if period == 'test':
            if missing_ratio is not None:
                self.masking = self.mask_data(seed)
            elif predict_length is not None:
                masks = np.ones(self.samples.shape)
                masks[:, -predict_length:, :] = 0
                self.masking = masks.astype(bool)
            else:
                raise NotImplementedError()
        self.sample_num = self.samples.shape[0]

    def __getsamples(self, data, proportion, seed):
        x = np.zeros((self.sample_num_total, self.window, self.var_num))
        for i in range(self.sample_num_total):
            start = i
            end = i + self.window
            print(start,end)
            print(data.shape)
            print(data[start:end, :].shape)
            '''
            0 178
            (1127, 178)
            (178, 178)
            '''
            x[i, :, :] = data[start:end, :]-----------报错位置，shape not match

        train_data, test_data = self.divide(x, proportion, seed)

        if self.save2npy:
            if 1 - proportion > 0:
                np.save(os.path.join(self.dir, f"{self.name}_ground_truth_{self.window}_test.npy"), self.unnormalize(test_data))
            np.save(os.path.join(self.dir, f"{self.name}_ground_truth_{self.window}_train.npy"), self.unnormalize(train_data))
            if self.auto_norm:
                if 1 - proportion > 0:
                    np.save(os.path.join(self.dir, f"{self.name}_norm_truth_{self.window}_test.npy"), unnormalize_to_zero_to_one(test_data))
                np.save(os.path.join(self.dir, f"{self.name}_norm_truth_{self.window}_train.npy"), unnormalize_to_zero_to_one(train_data))
            else:
                if 1 - proportion > 0:
                    np.save(os.path.join(self.dir, f"{self.name}_norm_truth_{self.window}_test.npy"), test_data)
                np.save(os.path.join(self.dir, f"{self.name}_norm_truth_{self.window}_train.npy"), train_data)

        return train_data, test_data

Looking for your reply! Thank u!

**Comment by Y-debug-sys** [comment]
The corrected `read_data` code is shown below:
```
def read_data(filepath, name=''):
    data = io.loadmat(filepath + '/pseudo_labels_epilepsy.mat')['Epilepsy']
    scaler = MinMaxScaler()
    scaler = scaler.fit(data.reshape(-1,))
    return data.reshape(data.shape[0], -1, 1), scaler
```

Then reuse other codes in [mujoco_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/mujoco_dataset.py) please. Just replace [```self.rawdata, self.scaler = self._generate_random_trajectories(n_samples=num, seed=seed)```](https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Utils/Data_utils/mujoco_dataset.py#L42C37-L42C97) with ```self.rawdata, self.scaler = self.read_data(filepath, name)```

Do not segment your data using `__getsamples` again !

**Comment by holydick99** [comment]
> 更正后的代码如下所示：`read_data`
> 
> ```
> def read_data(filepath, name=''):
>     data = io.loadmat(filepath + '/pseudo_labels_epilepsy.mat')['Epilepsy']
>     scaler = MinMaxScaler()
>     scaler = scaler.fit(data.reshape(-1,))
>     return data.reshape(data.shape[0], -1, 1), scaler
> ```
> 
> 然后请重复使用 [mujoco_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/mujoco_dataset.py) 中的其他代码。只需替换为 [](https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Utils/Data_utils/mujoco_dataset.py#L42C37-L42C97) .`self.rawdata, self.scaler = self.read_data(filepath, name)`
> 
> 不要再次使用对数据进行细分！`__getsamples`

thanks for your answer!

**Comment by holydick99** [comment]
@Y-debug-sys 
thanks for your help, I have modify my code, but error happened like I show. In new code I don't know how this error occur.
-----------------------------------------------------
self.rawdata, self.scaler = self.read_data(data_root)
        print(self.rawdata.shape)
        if scalar is not None:
            self.scaler = scalar

        self.period, self.save2npy = period, save2npy
        self.samples = self.normalize(self.rawdata)
        # print(self.samples.shape)
        self.sample_num = self.samples.shape[0]
-------------------------------------------------------------------------------------------------
File ~/Diffusion-TS-test/Utils/Data_utils/Epilepsy_dataset.py:128, in EpilepsyDataset.__len__(self)
    127 def __len__(self):
--> 128     return self.sample_num

AttributeError: 'EpilepsyDataset' object has no attribute 'sample_num'
--------------------------------------------------------------------------------------------------

**Comment by Y-debug-sys** [comment]
Send your data to my email: yxy5315@gmail.com. I will provide the corresponding code. Thanks !

**Comment by holydick99** [comment]
> [yxy5315@gmail.com](mailto:yxy5315@gmail.com).

I have send my data to your email, appreciate again!

**Comment by holydick99** [comment]
> > The corrected `read_data` code is shown below:
> > ```
> > def read_data(filepath, name=''):
> >     data = io.loadmat(filepath + '/pseudo_labels_epilepsy.mat')['Epilepsy']
> >     scaler = MinMaxScaler()
> >     scaler = scaler.fit(data.reshape(-1,))
> >     return data.reshape(data.shape[0], -1, 1), scaler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then reuse other codes in [mujoco_dataset.py](https://github.com/Y-debug-sys/Diffusion-TS/blob/main/Utils/Data_utils/mujoco_dataset.py) please. Just replace [`self.rawdata, self.scaler = self._generate_random_trajectories(n_samples=num, seed=seed)`](https://github.com/Y-debug-sys/Diffusion-TS/blob/8972c299eda8911a393023ee8ef14ac0a54a9c82/Utils/Data_utils/mujoco_dataset.py#L42C37-L42C97) with `self.rawdata, self.scaler = self.read_data(filepath, name)`.
> > Do not segment your data using `__getsamples` again !
> 
> Thanks for the author's reply. I am interested in this issue. May I ask why you recommend to use mujoco_dataset.py to process his own data instead of using real_datasets.py?

Hi, why the author recommend me to use the mujoco_dataset.py is due to my dataset is no need to use '__getsamples' segment data again

**Comment by lixus7** [comment]
But getsamples is only used once in real_datasets.py. I mean,  if you also define the def __getitem__ function, then you can refer to real_datasets.py too, is my understanding correct?

**Comment by Y-debug-sys** [comment]
![image](https://github.com/user-attachments/assets/97246ad7-865b-4e7b-886d-a57fc639385f)
![image](https://github.com/user-attachments/assets/60b75d41-5969-47b9-a102-5b63096aee7e)
![image](https://github.com/user-attachments/assets/0ba82255-ca38-48dc-af50-cc0637aeb67f)
