### ISSUE TITLE
关于模型扩散过程和去噪过程一些细节的疑问

### ISSUE THREAD

**Issue by AngerDark01** [Y-debug-sys/Diffusion-TS#66]
老哥你好，最近重新研究你的论文，里面没有找到前向过程的说明，遂有一些疑问：
1. 关于模型的结构的问题，我没搞懂这个编码解码部分在模型的哪个部分执行。有以下两个猜想，不太确定是哪种执行方式：
-- 1.  编码 - 前向扩散 - 反向扩散 - 解码
-- 2. 前向反向过程中每一步都执行一次编码解码

**Comment by AngerDark01** [comment]
好的，非常感谢

**Comment by AngerDark01** [comment]
![fig1](https://github.com/user-attachments/assets/113cf7b2-da8d-4400-bc6f-d963e3bdfedb)
da 但是我看这个结构图，在X_t  -> X_t-1过程中，也执行了编码和解码，这样不是表示每个时间步都要执行一次这个过程吗

**Comment by Y-debug-sys** [comment]
实际是X_t ->X_0 -> X_t-1，谢谢。

**Comment by AngerDark01** [comment]
X_0 -> X_t-1这个是生成的步骤吗
