### ISSUE TITLE
Clarification regarding conditional generation

### ISSUE THREAD

**Issue by saishankarn** [Y-debug-sys/Diffusion-TS#70]
Hi, from my understanding of the code, in line 303 of Models/interpretable_diffusion/gaussian_diffusion.py, the sample refers to x_{t-1}. However, within the langevin_fn, the input to the denoiser in line 390 is x_t and t. While execution, I believe the input is x_{t-1} (i.e., sample) and t. Is my understanding correct?

**Comment by Y-debug-sys** [comment]
Yes, you are correct.

**Comment by saishankarn** [comment]
The implementation refers to Eq. 11 in the paper. So, should it be t-1 as input in line 390?

**Comment by Y-debug-sys** [comment]
Hi. In fact, apart from the first or last sampling step, I think the process aligns with the equation overall.

**Comment by saishankarn** [comment]
Is this empirical? So, still the input in line 390 should be t-1, right?

**Comment by Y-debug-sys** [comment]
Yes, you're right.
