### ISSUE TITLE
如何设置预测的时序长度

### ISSUE THREAD

**Issue by GeroRoman** [Y-debug-sys/Diffusion-TS#74]
您好！
请问您的代码在进行时序预测的时候是如何确定预测的时序长度的？还有如何对保存的npy文件还原成输入的.csv文件？我目前在做一个可视化扩散模型的系统，想要在其中添加您的扩散模型进行结果的展示，我在想如何才能将npy文件在前端进行展示

**Comment by Y-debug-sys** [comment]
`python main.py --name {dataset_name} --config_file {config.yaml} --gpu 0 --sample 1 --milestone {checkpoint_number} --mode predict --pred_len {pred_len}` 中的 pred_len 为预测长度。关于.csv文件，见 [issue](https://github.com/Y-debug-sys/Diffusion-TS/issues/47)。
