### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Ersan11** [Y-debug-sys/Diffusion-TS#76]
你好！我在使用Tutorial0的时候遇到了以下的问题，损失值异常，我并不知道其中的原因是什么，您能给出一些建议么？
![image](https://github.com/user-attachments/assets/66b62093-8a19-477f-a8f6-2c7cc24fd61a)
![image](https://github.com/user-attachments/assets/b1744c65-9fc2-4449-8db2-236b849682c6)
![image](https://github.com/user-attachments/assets/7dafbba4-6846-455b-8fba-ffd64dc29119)
![image](https://github.com/user-attachments/assets/5f4e31c3-0d13-47ff-ad91-5283dad8a5ce)
![image](https://github.com/user-attachments/assets/13cb6021-2141-416c-950f-c573e9632966)

**Comment by Y-debug-sys** [comment]
请问是偶然现象吗？我试了，并没有梯度爆炸现象。
![image](https://github.com/user-attachments/assets/951d3b1d-8bdf-4eac-8300-d4ab750c6479)

**Comment by Y-debug-sys** [comment]
类似的问题见 https://github.com/Y-debug-sys/Diffusion-TS/issues/6

**Comment by Ersan11** [comment]
好的，谢谢你的建议，我用了自己的数据集没有梯度爆炸，应该是偶然现象。

**Comment by Ersan11** [comment]
好的，谢谢你的建议，我用了自己的数据集没有梯度爆炸，应该是偶然现象。
