### ISSUE TITLE
条件扩散

### ISSUE THREAD

**Issue by Ersan11** [Y-debug-sys/Diffusion-TS#77]
您好！我对你的条件模型的理解是通过原始数据（目标数据）进行指导生成的（目标数据）。我想使用你的模型实现，条件数据指导生成目标数据，不知道可不可以实现，能给出你的建议嘛？或者说用数据的其他维度的特征（条件数据）指导生成一个维度的特征（目标数据）可行吗？

**Comment by Y-debug-sys** [comment]
当然可以，修改生成过程中的指导函数即可，谢谢！

**Comment by Ersan11** [comment]
> 当然可以，修改生成过程中的指导函数即可，谢谢！

1.你说的是数据的其他维度的特征（条件数据）指导生成一个维度的特征（目标数据）这个方法可行是嘛？2.这个在你的模型里算是无条件任务嘛？3.另外对于修改生成过程中的指导函数,您能给出进一步建议么？谢谢！

**Comment by Y-debug-sys** [comment]
1. 可行，如果我没理解错的话就是改动库里mask的对象而已；2. 训练数据得完整，生成使用无条件模型即可；3. 见1，修改以下代码段 https://github.com/Y-debug-sys/Diffusion-TS/blob/13a2186e6442669f70afe07dcd3632466f6ee10a/Models/interpretable_diffusion/gaussian_diffusion.py#L392C1-L399C79

**Comment by Ersan11** [comment]
你好！1.如果使用无条件模型生成的话，它不是没有设计到mask的问题么？2.我现在先使用了一下Tutorial_0.ipynb训练了自己的数据集，结果如下，不知道是否还可以提高精度么，可以给一些建议嘛？因为我对比了一个样本的曲线图，发现差别还是很大，同如下图。3.生成的数据怎么进行反归一化，进行数据还原？4.现在我的数据集只有两个特征，后续我会加入新的特征，特征之间是存在联系的吧，可以互相指导生成的吧？5.因为数据的应用场景问题，是否可以给生成的数据添加限制条件（如指定生成的值的范围）
![image](https://github.com/user-attachments/assets/b46d4468-912c-4a97-beaa-3f60e2bd5aad)
![image](https://github.com/user-attachments/assets/596636db-9d07-4d7f-a858-8f24f84adc46)
![image](https://github.com/user-attachments/assets/d241c752-4662-4797-ae3a-c8c3840a9a16)
 
![image](https://github.com/user-attachments/assets/fdb9f5c7-57a8-4c06-a704-aedfbb18f5f7)
不好意思，我的工作进度较慢，没有及时对你的建议提供反馈，谢谢你的建议了！

> 1. 可行，如果我没理解错的话就是改动库里mask的对象而已；2. 训练数据得完整，生成使用无条件模型即可；3. 见1，修改以下代码段 https://github.com/Y-debug-sys/Diffusion-TS/blob/13a2186e6442669f70afe07dcd3632466f6ee10a/Models/interpretable_diffusion/gaussian_diffusion.py#L392C1-L399C79

**Comment by Y-debug-sys** [comment]
> 1.如果使用无条件模型生成的话，它不是没有设计到mask的问题么？4.现在我的数据集只有两个特征，后续我会加入新的特征，特征之间是存在联系的吧，可以互相指导生成的吧？

mask只在条件生成任务中用到，但需要指出的是，在训练时必须是完整的（包含所有特征的）数据，否则不能直接套用我们的方法。其次，你的这种联系必须是可以显示表达出来的，比如预测需要历史信息相同。

> 2.我现在先使用了一下Tutorial_0.ipynb训练了自己的数据集，结果如下，不知道是否还可以提高精度么，可以给一些建议嘛？因为我对比了一个样本的曲线图，发现差别还是很大，同如下图。

无条件生成这么对比是不科学的，完全随机的观察，二者很可能没有关系，类似问题可见 https://github.com/Y-debug-sys/Diffusion-TS/issues/20 。

> 3.生成的数据怎么进行反归一化，进行数据还原？

详见 https://github.com/Y-debug-sys/Diffusion-TS/issues/35 。

> 5.因为数据的应用场景问题，是否可以给生成的数据添加限制条件（如指定生成的值的范围）

可以试着加入惩罚项，当值超出时，加大生成过程中指导的 loss。

**Comment by Ersan11** [comment]
> 1. 可行，如果我没理解错的话就是改动库里mask的对象而已；2. 训练数据得完整，生成使用无条件模型即可；3. 见1，修改以下代码段 https://github.com/Y-debug-sys/Diffusion-TS/blob/13a2186e6442669f70afe07dcd3632466f6ee10a/Models/interpretable_diffusion/gaussian_diffusion.py#L392C1-L399C79

根据您的建议，我修改了以下部分代码中的infill_loss的计算，现在是有两个特征，我只指定的了其中一个特征计算infill_loss的值，这样算是一个特征指导另一个特征么？
![image](https://github.com/user-attachments/assets/698f0321-6f37-46c2-a86d-445a339ef6fe)

然后我做了预测任务，结果图如下，上面的特征是不参与infill_loss计算的。对于结果您能给出一些建议么？
![image](https://github.com/user-attachments/assets/0bfb2b81-9ef7-4a7d-9e36-3738b9502615)
