### ISSUE TITLE
Weighted Loss Implementation Question

### ISSUE THREAD

**Issue by zahir-w** [Y-debug-sys/Diffusion-TS#78]
Hi, I find that the train loss in your paper is down-weighted with the equation (9).
![image](https://github.com/user-attachments/assets/f45f269e-4fa1-4fbf-9781-418fddc81c6b)

But it seems that the code implementation for loss weight is the sqrt of the alphas and so on.
![image](https://github.com/user-attachments/assets/7850417f-a487-4ed1-8138-b965beb25fae)

I am wondering whether the implementation difference is due to the train stability or some reasons?

Best Regards,
Zahir Wang

**Comment by Y-debug-sys** [comment]
Hi, Zahir. These two are equivalent because the repo uses L1 loss, while the formula is MSE. Therefore, the weight is square-rooted. Thanks!

**Comment by zahir-w** [comment]
> Hi, Zahir. These two are equivalent because the repo uses L1 loss, while the formula is MSE. Therefore, the weight is square-rooted. Thanks!

Thanks! 
I understand that. Put the weights into the sqrt so get the square of that.

Best Regards,
Zahir Wang
