### ISSUE TITLE
请教Figure 3的获取方法

### ISSUE THREAD

**Issue by Zjh152** [Y-debug-sys/Diffusion-TS#79]
view_interpretability.ipynb中给出了对于一个模拟时间序列合成的解释方法。针对真实的时间序列，如Figure 3中的3个数据集合成结果，如何得到可解释的可视化结果呢？

**Comment by Y-debug-sys** [comment]
Trend，Seasonality&Residual 只是打印出来各个部分的输出而已，其中 Seasonality&Residual 为二者求和。

**Comment by Zjh152** [comment]
意即我可以从gaussian_diffusion.py中进行提取吗。

**Comment by Y-debug-sys** [comment]
仿照给出的 Jupter Notebook 演示调用就行，区别是周期残差加一起。

**Comment by Zjh152** [comment]
感谢。
