### ISSUE TITLE
Train for multiple data fragments

### ISSUE THREAD

**Issue by zahir-w** [Y-debug-sys/Diffusion-TS#80]
Hi, I am confused about how to train when there are multi time-series clips/slices for the only one object(such as one company stock). 
And I don't know whether they are continuous in time (probably not continuous).
It seems need to consider the dataset clips as the batch inputs?
Here is an example, the dataset have 10 sequences with different lengths. But they do both are from one object recording(not different object)
![image](https://github.com/user-attachments/assets/53f7ea8d-3535-43be-aed4-83f467a83f52)

Best Regards,
Zahir Wang

**Comment by Y-debug-sys** [comment]
Do you mean sliding each sequence into segments of the shape `(num_i, seq_length, 1)` and then combining them into `(num, seq_length, 1)`? I do think it’s feasible.

**Comment by zahir-w** [comment]
Like this, I have the seq(1-n) and i only know these seqs are from one original seq.
![image](https://github.com/user-attachments/assets/e0b3f0c4-438c-4649-8d74-0b4ac3357cfb)

**Comment by Y-debug-sys** [comment]
Thank you for your detailed and vivid illustration. Identifying where each sequence breaks is indeed a tricky issue, and it’s clearly beyond the scope of this repo. If the discontinuities can be tolerated or ignored, I think it’s OK to proceed directly with the approach mentioned above.
