### ISSUE TITLE
关于预测长度问题

### ISSUE THREAD

**Issue by GeroRoman** [Y-debug-sys/Diffusion-TS#81]
作者您好！
我在调试代码的时候发现，这里面的testdataset的数据路径是整个ETTh的数据集，为了把结果调整成和之前csv格式一样的数据，我对代码做了如下处理，详情见代码注释的反归一化那一行，但是我预测出的结果的数据yi'o一共有41737行，而我在test中设置的pred_len是1，请问这里面的pre_len是如何设置的，因为我在别的代码中见过别人设置的可以选择预测以小时为单位或者以天为单位，恳请作者指点
![image](https://github.com/user-attachments/assets/bec3368d-922a-49cf-b398-9c2cb8d131db)
![image](https://github.com/user-attachments/assets/31124249-978b-4bf2-93e4-c63f4a937940)
![image](https://github.com/user-attachments/assets/34c9ab71-fee1-4122-81ef-58868f5dda00)

**Comment by GeroRoman** [comment]
这个demo.csv是我自己设置的初始时间，我直接设置为原本数据集的第一行的时间，因为test的dataset是整个原数据集，但是超过了原数据集的长度（17421行）

**Comment by Y-debug-sys** [comment]
你好，结果数据包括历史窗口，后面pred_len个数据点为预测数据。

**Comment by GeroRoman** [comment]
作者您好，我不太确定这个预测长度是如何设置的，因为这个预测长度设置的是1，但是结果却是多预测了快三万条数据

**Comment by GeroRoman** [comment]
我还想请教一下如果预测结果超出原数据集的长度，那么损失函数如何判定呢？还是只作为具体生产应用中的参考数据？如果要对预测结果进行评估是不是只能用数据集范围内的数据？

**Comment by Y-debug-sys** [comment]
> 作者您好，我不太确定这个预测长度是如何设置的，因为这个预测长度设置的是1，但是结果却是多预测了快三万条数据

前两万多条都是历史窗口，最后一位为预测结果。


> 我还想请教一下如果预测结果超出原数据集的长度，那么损失函数如何判定呢？还是只作为具体生产应用中的参考数据？如果要对预测结果进行评估是不是只能用数据集范围内的数据？

训练不针对预测，为无条件模型的预测任务，故与损失函数无关。此外，本库只支持训练时模型生成长度以内的预测长度。评估指的误差？如果是，必须得有真实数据。

**Comment by GeroRoman** [comment]
作者您好，
我也是hfut的学生，目前在研究扩散模型领域，请问能方便加一下联系方式吗？关于输出结果的细节有一些问题想要和您讨论一下，我的联系方式：
wx：Xiaowangzi_Oops
tel：15837696139
qq：675999408

**Comment by Y-debug-sys** [comment]
欢迎邮箱联系！

**Comment by GeroRoman** [comment]
作者您好！
![image](https://github.com/user-attachments/assets/ad218fd7-9990-481f-ad7d-cafc829d8d38)
我主要不理解的一点是，这里面debug显示测试数据集的长度是17420，其中的rawdata是对应的原本的数据集，那么sample_num是1739是如何计算得到的，下面的sample_num_total又是如何得到的，samples的大小为[1739，24，7]是不是意味着采样了1739次，对应pred_len=1也就是产生1739条数据，那么对应的数据的时间点是怎么确定的呢？

**Comment by GeroRoman** [comment]
我目前在做的工作需要对结果在前端上显示，所以需要弄清楚结果的结构，能否请您指点一下，如果有打扰到，敬请谅解

**Comment by Y-debug-sys** [comment]
请问yaml的比例是不是0.9？这样表示测试集为10%，即 17420/10 条测试数据。

**Comment by GeroRoman** [comment]
作者您好！yaml的test的比例是0.9，我的预测产生的数据为1739*24=41736条数据，会不会是因为我的预测长度是1，这里代码理解的是一天24小时，也就是一次预测生成的长度是24，但是我的总数据长的是17420，那么用于预测的数据长度应该是1742，为什么会少3条呢？我的理解的维度应该是1742,24,7

**Comment by Y-debug-sys** [comment]
由于滑动窗口制作训练样本，实际样本总数没有17420，如下：

![image](https://github.com/user-attachments/assets/fa732223-1b6c-4ba4-aacc-bc2a62cb18c3)

**Comment by GeroRoman** [comment]
![image](https://github.com/user-attachments/assets/e8b06680-a9b7-494d-a117-83c0ee629d30)
作者您好！我在调试的时候把预测长度换为77，为什么中间那个维度还是24呢？我之前把预测长度设为1为认为是一天24小时，为什么把预测长度换为77后中间的维度还是24呢？这个24有什么具体的意义吗？

**Comment by GeroRoman** [comment]
如果24是对应window的24，那么预测长度这个参数的设置的意义是什么呢？

**Comment by GeroRoman** [comment]
作者您好，我通过调试发现中间的维度代表window，那么我想问这里的预测值对应求得的1737,24,7中的哪一部分呢？预测长度的作用在哪里体现呢？

**Comment by Y-debug-sys** [comment]
window是训练时的序列生成长度，预测长度应该小于window（但是超过了等同于无条件生成，即无历史信息），结果保存的是包含历史信息（即全部window长度）的数据，可以修改代码只保存后预测长度位的数据，谢谢！

**Comment by GeroRoman** [comment]
作者您好，我在您提供的solar_nips_forecasting.ipynb文件中，看到的对于预测结果的用法是：
![image](https://github.com/user-attachments/assets/99d4c30e-88da-42f5-9139-3d246d0f9474)
感觉是不是和您说的修改代码有所不一样，
![image](https://github.com/user-attachments/assets/7793d865-9ccb-4f01-ad97-5bdbf1eb5cc0)
![image](https://github.com/user-attachments/assets/e1932ea1-82bb-4d73-8188-ae727ccffcd1)
这里代码是不是出现了一点问题，我在把mode设置成predict的时候，跑出来的结果显示是imputation done
![image](https://github.com/user-attachments/assets/af0b2583-ec9f-453f-b7b1-d5ebd99b3b9a)

**Comment by GeroRoman** [comment]
会不会是我这里默认做的就是imputation的任务

**Comment by Y-debug-sys** [comment]
代码没有问题，这里的插入和预测没有本质区别。

**Comment by GeroRoman** [comment]
我理解了，这里是采用数据重构的方法生成数据，所以两种方法没有区别，但是我想问一下，这里采样得来的维度是24，那么是不是说明这里都是窗口中的数据，而预测的数据没有保留？请问如何修改代码才能只保存预测出来的数据呢？像solar_nips_forecasting.ipynb文件中
plt.plot(range(seq_length-pred_length-1, seq_length), sample[0, -pred_length-1:, -idx], color='r', linestyle='solid', label='Prediction')
可以直接在结果中找到预测出的数据？

**Comment by GeroRoman** [comment]
作者您好!
我在通过保存不同数据发现，前24个数据都是一样的，第25个数据是变化的，与之对应我的window和pre_len，非常感谢作者愿意不厌其烦地提供帮助，祝您科研顺利，生活愉快！

**Comment by Y-debug-sys** [comment]
好的，感谢！
