### ISSUE TITLE
关于solar_nips数据集

### ISSUE THREAD

**Issue by GeroRoman** [Y-debug-sys/Diffusion-TS#82]
![image](https://github.com/user-attachments/assets/2180f4d4-e0c8-4f07-bbc4-bf58dcdbfac6)
作者您好，这是我根据get_dataset函数下载到的数据集，请问为什么这里的start都是一个时间，里面的target又是什么含义？

**Comment by Y-debug-sys** [comment]
你好，关于这个数据集，我完全使用的对比方法 [SSSD](https://github.com/AI4HealthUOL/SSSD) 的源码和处理方式。

**Comment by Y-debug-sys** [comment]
详见 https://github.com/AI4HealthUOL/SSSD/blob/main/docs/instructions/Solar/updated_solar.ipynb，当然你也可以查看官方库的报告。
