### ISSUE TITLE
main.py issues

### ISSUE THREAD

**Issue by zyd98123** [Y-debug-sys/Diffusion-TS#9]
Hello author, I have this problem“FileNotFoundError: [Errno 2] No such file or directory: 'Checkpoints_energy_24\\checkpoint-10.pt” when I run your main program, but I am sure that your data does not provide such a file. How can I get it?

**Comment by Y-debug-sys** [comment]
Hi, we do not provide pre-trained models in this repository. You may need to train model first before sampling or imputation, 
by running 
~~~bash
$ python main.py --name {name} --config_file {config.yaml} --gpu 0 --train
~~~
